### ISSUE TITLE
Security Audit

### ISSUE THREAD

**Issue by armaniferrante** [oasislabs/react-native-web3c#3]
Notes for @bennetyee. 

react-native-web3c builds a babelified and webpacked version of web3c.js, replacing all node specific packages with browserified versions so that it will run on mobile.

* Webpack config: https://github.com/oasislabs/react-native-web3c/blob/master/webpack.config.js
* Simple example of how it could be used in a react-native app: https://github.com/oasislabs/react-native-web3c/blob/master/examples/Counter/App.js#L4

**Comment by bennetyee** [comment]
lgtm, but not sure i'd trust my eyeballs since i am not js fluent.  nothing jumped out at me.

**Comment by armaniferrante** [comment]
Thanks @bennetyee. Closing.
