### ISSUE TITLE
minor style nit: identifier name

### ISSUE THREAD

**Issue by bennetyee** [oasislabs/react-native-web3c#4]
https://github.com/oasislabs/react-native-web3c/blob/e488dce20fce6d6fa0d955ff591e5d2de91c2c3d/examples/Counter/App.js#L19

I don't know if it is a common javascript idiom, but I tend to not like identifiers that differ in case only.  `Web3c` is `react-native-web3c` import, and `web3c` is an object created from it with `new`.  It reduces readability, esp w/ smaller fonts.

**Comment by armaniferrante** [comment]
Fair point. I don't think this is generally a common js idiom, but it is indeed unique/common usage with web3.js for better or worse, as the provider has to be set before it can do anything useful. We'll leave this as is for now. Closing.
